### ISSUE TITLE
Supported lighting types

### ISSUE THREAD

**Issue by jonnyfarmer** [maxwellhadley/node-red-contrib-rfxcom#10]
I'm trying to control a Energenie plug socket which can be controlled from RFXmgr as a Lighting1 object with a house code of A and a device of 1 (or + for all).

I've tried lighting1, LIGHTING1 and L1 as part of the topic (e.g. 'lighting1/A/1') but all variations result in in a rfx-lights-out : device type 'xxx' is not supported

Sorry if I'm being particularly thick here but I'm stumped.

Thanks

Jonny

**Comment by maxwellhadley** [comment]
The device type will be either 'ENERGENIE_ENER010' or 'ENERGENIE_5_GANG', depending on the socket type. The easiest way to check is to temporarily add an rfx-lights-in node, set to listen to any address, to your flow, and connect its output to a debug node. Use the remote control (that presumably came with the socket) to operate your socket and look at the topic shown in the debug panel

I hope this gets you going!

Max

**Comment by jonnyfarmer** [comment]
Many, many thanks Max

Did exactly what you suggested and have it working.

Absolutely marvellous - thanks again for creating the node - much
appreciated.

Kind regards

Jonny

**Comment by maxwellhadley** [comment]
Glad it works for you!
