### ISSUE TITLE
Somebody use this device?

### ISSUE THREAD

**Issue by vampywiz17** [maxwellhadley/node-red-contrib-rfxcom#101]
Hello there,

I would like to buy a Milight bulb and a remote.

https://www.milight.com/milight-5w-rgbw-e14-screw-iphone-ios-android-controlled-light/

https://www.milight.com/milight-rgbw-remote/

my idea is that i able to control the bulb with remote locally and use RFXcom to control it with node-red.

My question is that somebody have any experiance that rfxcom support Milight devices? It not write it directly on the documentation but i found this integration guide (with openhab) that say it could be possible.

https://genetx.tweakblogs.net/blog/13097/aan-de-slag-met-openhab-2-rfxcom-en-milight

**Comment by maxwellhadley** [comment]
There is no mention of _Milight_ in either the user or developer documentation of the RFXCOM. The description of the Milight remote states it uses a 2.4GHz radio, as opposed to the 434MHz of the RFXCOM, so it would not seem to be possible. For some reason Google Translate is not working on the blog page you linked, so I can't understand what it says :(
