### ISSUE TITLE
ByronSX doorbell chime in Doorbell out

### ISSUE THREAD

**Issue by stevieby** [maxwellhadley/node-red-contrib-rfxcom#108]
Hi

Have been trying out this library and so far it's working great for my lighting needs with Home Easy and Lightwave RF.  However I have a spare ByronSX chime that I also can trigger from RFXCom Mgr and was hoping to rig this up to my NODE-RED as well.

For example I trigger this from RFXCOM Mgr with this

11/10/2020 05:11:45:609= Chime command: 07 16 00 34 00 04 02 00 
================================================
Packettype    = Chime
subtype       = Byron SX
Sequence nbr  = 52
ID            = 0004 decimal:4
Sound         = SX21 Solo
Signal level  = +10 dBm

So far I have looked through the documentation and set it the address as BYRON_SX/0x0004 with a Payload of 1 for the sound.  However no matter what I do it does not seem to trigger the bell.  I've tried other addresses such as BYRON_SX/0x000400 as well but so far no luck.

Any thoughts on what I might be doing wrong?

thanks

Steve

**Comment by maxwellhadley** [comment]
It works here when I try it, as far as I can tell without an actual doorbell.

Can you please enable debug messages in the rfxtrx-port configuration node, and post the console output (if any) that appears in response to your doorbell message?

**Comment by stevieby** [comment]
Thanks got it working, turns out my ID had changed to 5 and I was using 4.  
Apologies for raising the issue and thanks for the library - looking to hook this into home assistant via mqtt and so far making this pretty easy
