### ISSUE TITLE
Sending Dimmer brightness to an AC dimmer

### ISSUE THREAD

**Issue by PuckeyP** [maxwellhadley/node-red-contrib-rfxcom#113]
I have a problem with sending brightness information to an AC type dimmer with the rfx-light out node payload. Cannot find any information on this topic. "On" and Off" works fine. Can you point me in the right direction.
Thx!!

**Comment by maxwellhadley** [comment]
There is some information in the help text for the node:

> Typical commands are 'On' & 'Off' (or equivalently 1 & 0, or <b>true</b> & <b>false</b>); 'Bright' or 'Dim+' to increase
> brightness; 'Dim' or 'Dim-' to reduce brightness; 'level <i>percentage</i>%' or 'level <i>number</i>' (where <i>number</i>
> is a value between 0 and 1) to set the brightness.

So a payload of something like `level 62%` will work if the device accepts any sort of numeric input - the percentage is translated according to whatever range of numbers the device subtype specifies it can handle. Some subtypes only accept increase and decrease commands, in which case a payload of `bright` will increase and `dim` will decrease (or just `+` and `-`)

**Comment by maxwellhadley** [comment]
I'm glad you got it going OK!
