### ISSUE TITLE
Odd behaviour for MCZ stove

### ISSUE THREAD

**Issue by Webbeh** [maxwellhadley/node-red-contrib-rfxcom#116]
Hi.

I've made a box to control MCZ pellet stoves. It uses a raspberry pi and the new RFXCOM versions (batch 21xx), with ProXL 1 firmwares (version 1044).

Everything seems to work fine, except... When the fan speed is at "1", this node says that the command isn't recognized.

![image](https://user-images.githubusercontent.com/1530837/131507437-42524927-e347-4f7b-994e-939d43084054.png)
![image](https://user-images.githubusercontent.com/1530837/131508948-6b74312b-4cf8-441b-9247-9b928bc36af9.png)
![image](https://user-images.githubusercontent.com/1530837/131508957-3988381d-a600-46b2-9133-b74d6466ea01.png)

Whether fanSpeed is an array of the right size, an array of the wrong size, or a simple number, I get that error whenever the model is "1 fan".

Node-red 1.2.5
node-red-contrib-rfxcom 2.11.3

**Comment by maxwellhadley** [comment]
A fan speed of 1 is accepted only if the flame power is set to 2 or less, not if it is 3 or more. Presumably this is to prevent overheating?

This behaviour is embedded within the RFXCOM itself, not the node. I hope this helps!

**Comment by Webbeh** [comment]
Oh wow, can't believe I missed that.

I did that check but somehow removed it, didn't think to check...

Well, thanks...

**Comment by maxwellhadley** [comment]
This behaviour doesn't seem to be documented anywhere I could find, although I did find a warning about using fan speed 0 with flame power other than 1.

**Comment by Webbeh** [comment]
I believe I saw it either in the SDK or in the quick start manual. Anyway thanks.

**Comment by Webbeh** [comment]
![image](https://user-images.githubusercontent.com/1530837/131629673-a583c459-f8fe-418c-afb5-7a0f989bc72b.png)

Couldn't find the limitations anymore but there's some details for anyone who find this issue later.

**Comment by maxwellhadley** [comment]
That is similar to what I have in the SDK documents, but not exactly the same. The behaviour with fan speed = 1 isn't documented though. Thanks for posting - this will be a useful reference
