### ISSUE TITLE
Sending RAW transmit command

### ISSUE THREAD

**Issue by MPowerData** [maxwellhadley/node-red-contrib-rfxcom#117]
The supporting package `node-rfxcom` which `node-red-contrib-rfxcom` uses (and which I also maintain, and wrote a large part of) can support raw transmit packets. I will have a think about the best way to add this to `node-red-contrib-rfxcom`. 

Hi all,

Does anyone know if the above is implemented and how to configure this in node-red?

I would like to do a RAW transmit command using the HEX key generated bu RFXmgr.

There is no other way to do this, as the RFX only recognize the undecoded command.

Thank you for the help!

**Comment by MPowerData** [comment]
Anyone?

@maxwellhadley , can you please let me know if this is possible?

**Comment by MPowerData** [comment]
Thank you for your comment. 

I will keep an eye on this issue, as it would be really great when this is possible...

**Comment by MPowerData** [comment]
Hi Max, did you find any time to work on this?

**Comment by maxwellhadley** [comment]
I finally have a new rfx-raw-out node working, just a few more details to sort out. I hope to publish the new version in the next week or two

**Comment by MPowerData** [comment]
> I finally have a new rfx-raw-out node working, just a few more details to sort out. I hope to publish the new version in the next week or two

Wow! That is great news! Please let me know if I can be of any help...

**Comment by maxwellhadley** [comment]
I have just published version 2.12.0 which adds a new rfx-raw-out node (but I forgot to mention it in the README!)

**Comment by MPowerData** [comment]
Hi Max, I am playing around with the new node, but I don't seem to get it working.

Below the output of a command I sent through the RFXmngr. 

05/02/2023 08:43:26:004= RAW transmit command: AC 7F 00 03 07 20 8C 10 EA 01 85 02 7F 01 88 02 7C 01 82 06 96 01 8B 02 7D 01 8B 02 74 01 94 02 7E 01 7E 06 A6 01 80 02 96 01 8B 02 7F 01 87 02 88 01 78 06 9B 01 87 02 81 01 87 02 83 01 79 06 92 01 88 06 99 01 81 06 A4 01 8C 02 79 01 8F 02 92 01 76 02 82 01 86 02 81 01 86 02 79 01 8C 02 84 01 86 02 7F 01 7D 06 AE 01 85 02 76 01 8F 02 80 01 86 02 81 01 88 02 89 01 7C 02 7F 01 81 06 A8 01 7C 02 7F 01 88 02 A9 01 76 06 9F 01 77 06 A2 01 82 02 7B 01 85 06 98 01 8B 02 79 01 8E 02 7C 01 81 06 AA 01 77 02 7C 01 88 27 10 
================================================
Packettype    = RAW Packet
Packet Length = 172
subtype       = RAW packet
Sequence nbr  = 3
Repeat        = 7
Nbr of pulses = 42
8332  4330  389  639  392  636  386  1686  395  637  395  628  404  638  382  1702  384  662  395  639  391  648  376  1691  391  641  391  643  377  1682  392  1689  385  1700  396  633  399  658  374  642  390  641  390  633  396  644  390  639  381  1710  389  630  399  640  390  641  392  649  380  639  385  1704  380  639  392  681  374  1695  375  1698  386  635  389  1688  395  633  398  636  385  1706  375  636  392  10000   

How would I configure this in the node?

Can you maybe share some example config with me?

Thanks in advance!

**Comment by maxwellhadley** [comment]
Here's how it's done:

A simple flow:

![image](https://user-images.githubusercontent.com/6557194/217073599-9e64925c-b12a-48b9-9bb5-9579b76ab2c1.png)

I have configured the rfx-raw-out node like this:

![image](https://user-images.githubusercontent.com/6557194/217073770-cb2778e5-aab5-4aa4-8057-8fabae69112b.png)

Click on the pencil button at the side of the 'Devices' line to open the Device List editor. If you haven't created a device list, you will need to add a new one and give it a name:

![image](https://user-images.githubusercontent.com/6557194/217074209-4b943c22-da03-45a4-a594-de85b0735409.png)

Now click 'add new device', and enter a topic and payload of your choice which, when sent to the rfx-raw-out node, should send the raw data. I chose 'RAW/1' as the topic and 'Test' as the payload (note the topic must start with 'RAW/')

![image](https://user-images.githubusercontent.com/6557194/217074762-4db4acf8-df75-4ef4-ac11-ce67b711884e.png)

Now click on the pencil icon next to the 'Pulse Data' box. This opens an editor into which you can paste the (decimal) pulse time data from your example:

![image](https://user-images.githubusercontent.com/6557194/217075145-6d2e0e6a-7e9e-4d6c-95d4-ba08f56d1cde.png)

Now click OK, and set the number of repeats to 7 (you can see the start of the pulse data now shows in its box):

![image](https://user-images.githubusercontent.com/6557194/217075448-e7c6f946-2025-4234-98ca-fcc8961c97d3.png)

Click 'Update' and 'Done' and deploy the changed flow. Now, each time you send a message with topic RAW/1 and payload Test to the rfx-raw-out node, it will transmit the pattern. My flow copies the triggering message to the debug node:

![image](https://user-images.githubusercontent.com/6557194/217076268-90c24c63-2c4c-4f2d-ac39-cd3fa212d2b7.png)

If you have console debug enabled on the RFX device, you will see the message being queued, sent to the RFX, and acknowledged:

![image](https://user-images.githubusercontent.com/6557194/217078745-3629f153-e8ba-4c34-be7d-7d1962eb4165.png)

You can enter as many pulse patterns as you want in your Device List, so long as the Topic/Payload combination of each is unique.

I hope this helps!

**Comment by maxwellhadley** [comment]
Yes, the nodes automatically check the acknowledgment. You will get a warning message if the response is anything other than OK. For instance, if you send a transmit packet type of a type that isn't supported by the hardware/frimware combination.

**Comment by MPowerData** [comment]
> Yes, the nodes automatically check the acknowledgment. You will get a warning message if the response is anything other than OK. For instance, if you send a transmit packet type of a type that isn't supported by the hardware/frimware combination.

Great, thanks again for your support!
