### ISSUE TITLE
Nodered 3 incompatible?

### ISSUE THREAD

**Issue by Fernando-Checa** [maxwellhadley/node-red-contrib-rfxcom#123]
Can't seem to load the extension under NR 3.
![imagen](https://user-images.githubusercontent.com/1741686/182611013-2c1c78f8-9fbd-416e-9b48-b9ee51ed9032.png)

Any news on an update?
Thanks in advance

**Comment by maxwellhadley** [comment]
While I haven't moved to NodeRED 3 yet, as far as I know there shouldn't be a problem.

I found a few topics on the forum that refer to this same ERR_DLOPEN_FAILED error:

- [https://discourse.nodered.org/t/node-red-contrib-noble-bluetooth-err-dlopen-failed/55810](url)
- [https://discourse.nodered.org/t/node-red-contrib-i2c-is-unsupported/60753](url)
- https://discourse.nodered.org/t/sudo-command-not-found/61572

Maybe one of these might provide a clue. If not, could you please supply a bit more detail to help me troubleshoot.

**Comment by Fernando-Checa** [comment]
Thanks for your time.
I finally fixed it by uninstalling and reinstalling.
Also had to uninstall dashboard extention. I don't know why but there was a conflic.



Regardso,
[m1.png]

Fernando Checa Manrique de Lara
ARQUITECTO

***@***.***

[m2.png]


On 07/08/2022 19:54:50, Max Hadley ***@***.***> wrote:
While I haven't moved to NodeRED 3 yet, as far as I know there shouldn't be a problem.
I found a few topics on the forum that refer to this same ERR_DLOPEN_FAILED error:
* https://discourse.nodered.org/t/node-red-contrib-noble-bluetooth-err-dlopen-failed/55810 [url]
* https://discourse.nodered.org/t/node-red-contrib-i2c-is-unsupported/60753 [url]
* https://discourse.nodered.org/t/sudo-command-not-found/61572 [https://discourse.nodered.org/t/sudo-command-not-found/61572]
Maybe one of these might provide a clue. If not, could you please supply a bit more detail to help me troubleshoot.

**Comment by maxwellhadley** [comment]
Glad to hear you got it going!
