### ISSUE TITLE
RAW command

### ISSUE THREAD

**Issue by Fernando-Checa** [maxwellhadley/node-red-contrib-rfxcom#125]
I've seen a couple of comments about sending/receiving raw data.
Any advance in the matter?
Here is what I get from RFXmngr using the undec protocol (the device is Faro ceiling fan):

`19/10/2022 12:35:09:720= FC7F00010000DF11CA010103C000F003C100F403BD00F203BF00F103C000F403BE00F003C200EF03C100F003C000F203BF00F303BD00F403C000F303BE00F303BE00F403BE00F103BF00F003C4034A016600EF03C2034C016800EE03C100F003C0034B016900EF03BE00F303BD00F103C3034A016B0348016600EF03C0034C016500F103C100F203BE00F411C8010203BF00F303BF00F103C200F103BF00F003C100F203BB00F503BD00F603C000F003BE00F203C000F003C200F103BF00F203C000EF03C400EF03C000EF03BF00F503BD0350016400EF03BF034B016A00ED03C000EF03BF0350016A00ED03BE00F103C000F203BD034F016A0345016A
Packettype    = RAW Packet
Packet Length = 252
subtype       = RAW packet
Sequence nbr  = 1
Repeat        = 0
Nbr of pulses = 62
223  4554  257  960  240  961  244  957  242  959  241  960  244  958  240  962  239  961  240  960  242  959  243  957  244  960  243  958  243  958  244  958  241  959  240  964  842  358  239  962  844  360  238  961  240  960  843  361  239  958  243  957  241  963  842  363  840  358  239  960  844  357  241  961  242  958  244  4552  258  959  243  959  241  962  241  959  240  961  242  955  245  957  246  960  240  958  242  960  240  962  241  959  242  960  239  964  239  960  239  959  245  957  848  356  239  959  843  362  237  960  239  959  848  362  237  958  241  960  242  957  847  362  837  362   
------------------------------------------------
19/10/2022 12:35:11:034= FC7F01020000EF03BF034B016900EF03BF00F003BE00F711C7010103C000F303BF00F103BF00F203BF00F103C200EE03C100F203C200EF03C100F203BE00F303BE00F103C300EF03C100F003C300EF03BF00F203C100F003BF00F303BD034E016900EF03BF034C016700EE03C200F103BE034D016700EE03C000F203BE00F303BF034D01680349016900EC03BF034C016B00EC03C100EF03C300F611C6010203C200EF03C100F103C400ED03C200EF03C300EF03C100F103BE00F203C200F003BD00F503C200EE03BF00F003C300F003C000F203C000F003C400ED03C000F203C0034C016A00ED03BD0350016B00E903BF00F303BF034E016700EE03BE
Packettype    = RAW Packet
Packet Length = 252
subtype       = 2nd RAW packet
Sequence nbr  = 2
Repeat        = 0
Nbr of pulses = 62
239  959  843  361  239  959  240  958  247  4551  257  960  243  959  241  959  242  959  241  962  238  961  242  962  239  961  242  958  243  958  241  963  239  961  240  963  239  959  242  961  240  959  243  957  846  361  239  959  844  359  238  962  241  958  845  359  238  960  242  958  243  959  845  360  841  361  236  959  844  363  236  961  239  963  246  4550  258  962  239  961  241  964  237  962  239  963  239  961  241  958  242  962  240  957  245  962  238  959  240  963  240  960  242  960  240  964  237  960  242  960  844  362  237  957  848  363  233  959  243  959  846  359  238  958   
------------------------------------------------
19/10/2022 12:35:12:387= AC7F02030100F303BF00F303C00349016A0348016A00ED03BE034E016A00EA03C100F103C200F211CB010003BD00F203BF00F003C200F403C000EF03C200F003BD00F603BA00F503BF00F203BD00F503BB00F603BD00F603BE00F003C100F103BE00F203BD00F503BF00F103BE034E016800EE03BE0350016600EF03C000EF03C0034A016B00EC03C000F003C100EF03C2034A016C0346016800EE03BF034D016900ED03C400EF03BE00F50000
Packettype    = RAW Packet
Packet Length = 172
subtype       = 3rd RAW packet
Sequence nbr  = 3
Repeat        = 1
Nbr of pulses = 42
243  959  243  960  841  362  840  362  237  958  846  362  234  961  241  962  242  4555  256  957  242  959  240  962  244  960  239  962  240  957  246  954  245  959  242  957  245  955  246  957  246  958  240  961  241  958  242  957  245  959  241  958  846  360  238  958  848  358  239  960  239  960  842  363  236  960  240  961  239  962  842  364  838  360  238  959  845  361  237  964  239  958  245  0   `

**Comment by maxwellhadley** [comment]
I finally have a new rfx-raw-out node working, just a few more details to sort out. I hope to publish the new version in the next week or two

**Comment by maxwellhadley** [comment]
I have just published version 2.12.0 which adds a new rfx-raw-out node (but I forgot to mention it in the README!)
