### ISSUE TITLE
Please add support for new feature in Firmware 1028

### ISSUE THREAD

**Issue by jag100UK** [maxwellhadley/node-red-contrib-rfxcom#126]
I've been in contact with Birt from RFXCom and he's released a firmware update to support the "Unit" for Blinds 1 T11 ASP.

My device is a RFXtrx433 Type 1, but he's release the update for RFXtrx433E too.

Previously the RFXCom treated communication with the blind on unit ID 1 as "ALL", so if you have multiple blinds operated by the same remote, you could only control the blind on Unit ID 1.

RXFXCom now correctly interprets and transmits the Unit ID, so I can address each blind individually using RFXmgr.

It would be great if we can add support for this in node-red..

Currently, the payload doesn't include any Unit information in the address.. For example:

```
BLINDS_T11/0xA169A4 : msg.payload : string[4]
"Open"
```

Perhaps the address could be extended to include the unit?
For example
For all Units:-
`BLINDS_T11/0xA169A400`

For Unit ID 1
`BLINDS_T11/0xA169A401`

I can supply more outputs from RFXmgr if it helps coding

Many thanks

John

**Comment by maxwellhadley** [comment]
I've been very busy, but I am looking at this now, along with some other issues. But don't hold your breath!

**Comment by jag100UK** [comment]
No problem, Max.

I’d be happy to help with any testing, if you need a volunteer.

Thanks

John

Sent from my iPhone

On 27 Dec 2022, at 20:57, Max Hadley ***@***.***> wrote:

﻿

I've been very busy, but I am looking at this now, along with some other issues. But don't hold your breath!

**Comment by maxwellhadley** [comment]
A fix is in progress - I hope to publish a new version in the next couple of weeks

**Comment by jag100UK** [comment]
That’s Great!

Thanks Max

John

Sent from my iPhone

On 29 Jan 2023, at 20:03, Max Hadley ***@***.***> wrote:

﻿

A fix is in progress - I hope to publish a new version in the next couple of weeks

**Comment by maxwellhadley** [comment]
I have just published version 2.12.0 which adds support for the unit number to BLINDS_T11, among other things. Please chek it out: if it works for you I will close the issue

**Comment by jag100UK** [comment]
Thanks Max

This feels like a dumb question, but what difference am I expecting to see?

In the Pallet I have verified I have node-red-contrib-rfxcom version 2.12.0.

When I debug the value from rfx-blinds-in, it looks the same as before. There's no unit in the address or payload

Example:-
BLINDS_T11/0xA169A4 : msg.payload : string[4]
"Open"

On the rfx-blinds-out node, I don't see any way to specify the Unit.

Regards

John

**Comment by maxwellhadley** [comment]
You should add the unit number after the first part of the address, separated with a /

    BLINDS_T11/0xA169A4/1

That should work for sending commands. I thought it was working for receive as well when I tested it, but it looks like it still isn't. Please can you send me the byte sequence you get when you send a command from the remote and receive it on the RFXtrx? Either use RFXmgr, or enable debug output on the RFXCOM device and copy the output from the Node-RED console. I had to 'invent' a byte sequence based on the documentation to test receive operation, and it looks like I may have got it wrong :(

**Comment by jag100UK** [comment]
That's great, "Blinds out" works.

Here's what I receive using RFXmgr.

I notice that RFXmgr is displaying the Unit Number 1 value higher than the remote, but I think this is just a display bug.

The messages below are sent from a Louvolite R1922-6CH

All Blinds Open

03/02/2023 10:12:20:900= 09190B09A169A4000073

Packettype    = BLINDS1

subtype       = T11 ASP

Sequence nbr  = 9

id1-3         = A169A4 decimal:10578340

Unit          = All

Command       = Open

Signal level  = 7  -64dBm

Unit 1 Open

03/02/2023 10:13:31:536= 09190B15A169A4010073

Packettype    = BLINDS1

subtype       = T11 ASP

Sequence nbr  = 21

id1-3         = A169A4 decimal:10578340

Unit          = 2

Command       = Open

Signal level  = 7  -64dBm

Unit 2 Open

03/02/2023 10:14:15:202= 09190B18A169A4020073

Packettype    = BLINDS1

subtype       = T11 ASP

Sequence nbr  = 24

id1-3         = A169A4 decimal:10578340

Unit          = 3

Command       = Open

Signal level  = 7  -64dBm

Unit 6 Open

03/02/2023 10:14:43:957= 09190B1AA169A4060073

Packettype    = BLINDS1

subtype       = T11 ASP

Sequence nbr  = 26

id1-3         = A169A4 decimal:10578340

Unit          = 7

Command       = Open

Signal level  = 7  -64dBm

Many thanks

John

**Comment by maxwellhadley** [comment]
Version 2.12.1 just published: rfx-blinds-in should include the unit code in the message topic OK now

**Comment by jag100UK** [comment]
Thank you, Max this is working well now.

I really appreciate you taking the time to add support for this feature.

Regards

John

**Comment by maxwellhadley** [comment]
You're welcome!
