### ISSUE TITLE
Problem sending captured sequence of pulses with rfx-raw-out

### ISSUE THREAD

**Issue by cesarvoggithub** [maxwellhadley/node-red-contrib-rfxcom#133]
I'm trying to use node-rfxcom to send raw data captured with rfxmngr in Windows, but have failed miserably so far.

I was able to capture the sequence of bytes sent by a particular gate remote control used to open/close a garage gate here at my house, by using "undec on" in RFXmngr.exe.

I then created a simple unformatted txt file that I can load to have RFXmngr.exe transmit to the gate successfully.
The gate opens/closes everytime I playback the sequence in RFXmngr.exe, so I suppose I have the correct data.
Problem I'm facing is I don't know how to use that sequence in a rfx-raw-out node in Node-RED v3.0.2. It would be nice if a generic rfx-raw-in node exist, so I could somehow capture the raw data in Node-RED itself, and verify the captured data in a debug node, but unfortunately it seems there is no such node type currently.

I would be most grateful if someone would chime in and help me. TIA

PS: the data I captured with "undec on" looks like "402 1091 454 598 949 1093 452 606 948 610 946 1108 451 1115 450 622 949 612 947 1097 449 1104 450 1107 452 1110 451 618 949 621 950 623 950 1109 451 1101 455 1104 453 614 946 615 950 619 949 1120 452 1126 449 575 950 1055 451 556 948 1053 450 0". The RFXmngr.exe documentation tells me that I need to add a 0 7 before the above sequence and replace the last 0 in the sequence with a value greater than 8000 (I used 10000 as shown in an example in the same documentation) to play it back. As mentioned above, I did so and was able to open/close the gate sucessfully, but the following setup does not seem to work in Node-RED...

![243400956-a3f6ede9-496b-4e49-b751-7ffccf6692d1](https://github.com/maxwellhadley/node-red-contrib-rfxcom/assets/96385801/1de3a248-1486-4f31-86b3-6d46e2a16512)

![243401184-3d6c3856-cc65-4312-93df-0c347cf714ee](https://github.com/maxwellhadley/node-red-contrib-rfxcom/assets/96385801/6817deee-1c08-4a05-8fa3-3aaf13601930)

![243401121-0cf75f4c-3827-41c9-922c-65257b495e1c](https://github.com/maxwellhadley/node-red-contrib-rfxcom/assets/96385801/5751f6fe-1cc3-4199-a629-103736327bfd)

![243401285-7c3b6467-b313-4cfb-a5e2-d0b35dea3520](https://github.com/maxwellhadley/node-red-contrib-rfxcom/assets/96385801/9652200f-44c1-499c-b981-1f0c244f649a)

![243401352-165180dd-944d-4a2d-8de7-03d2f097132c](https://github.com/maxwellhadley/node-red-contrib-rfxcom/assets/96385801/afd4ce2c-1329-4041-b6a0-5b98a5b434ac)

**Comment by cesarvoggithub** [comment]
Never mind, I found what I was doing wrong. Thank you for your hard work.

**Comment by maxwellhadley** [comment]
OK good. Sorry for the slow response, just been moving everything to a new computer
