### ISSUE TITLE
Problem installing node on Node Red v3.0.2 on Dietpi v8.21.1 with Node.js v20.2.0

### ISSUE THREAD

**Issue by jonnyfarmer** [maxwellhadley/node-red-contrib-rfxcom#136]
For the first time in many years of using the rfxcom node (which is awsome!) I have had issues installing the node on Node Red v3.0.2 on Dietpi v8.21.1 and Node.js v20.2.0 and received an extensive error log which I have attached. After asking about this on the Node Red forum (as this is way out of my sphere of knowledge) I got the following guidance:

"Your log seems to suggest the version of serialport requied is 9.2.8, this is now very dated by the speed at which serialport gets developed, and it seems to have issues with a library of nan.

It could be that your using Node v20 (9.2.8 of serialport was around Node 10) so things have very likely become not compatible in your system.

My suggestion is to ask the author of node-red-contrib-rfxcom to update its dependencies and by extension the author of rfxcom"

Do you have any suggestions as to what I can try please?
[2023-09-19T21_49_45_647Z-debug-0.log](https://github.com/maxwellhadley/node-red-contrib-rfxcom/files/12674994/2023-09-19T21_49_45_647Z-debug-0.log)

**Comment by maxwellhadley** [comment]
FYI, I am also the only currently active maintainer of node-rfxcom, so it is all down to me. I'm very busy at the moment, I will try and get this all sorted when I get a chance. Please be patient with me for a while longer!

**Comment by maxwellhadley** [comment]
I've got a version of node-rfxcom using serialport 12.x.x running with NodeJS 18.x.x, plus many other long standing changes. I'm still working bringing node-red-contrib-rfx up to date, hopefully I will publish it sometime in the next week or so.

**Comment by maxwellhadley** [comment]
Version 2.13.0 now published to npm uses serialport 11.x.x, to retain compatibility with NodeJS v14. This should fix your issue
