### ISSUE TITLE
Is it possible to get readings from a BBQ thermometer

### ISSUE THREAD

**Issue by Bjsulla** [maxwellhadley/node-red-contrib-rfxcom#15]
I have an Maverick ET-732 BBQ thermometer that I am trying to get some readings from with no success. I have tried every node possible in the node-red-contrib-rfxcom and the RFXtrx433E is recognized and presenting the firmware version under the node but I get no readouts.

Sample reading from the RFXmngr:
Packettype    = BBQ
subtype       = BBQ1 - Maverick ET-732
Sequence nbr  = 22
ID            = 6FE1 decimal:28641
Sensor1 temp  = 23 °C
Sensor2 temp  = 26 °C
Signal level  = 7  -64dBm
Battery       = OK

Is it possible to get this working or is it functionality not yet present?
Regards
Bjorn

**Comment by maxwellhadley** [comment]
Currently the BBQ temperature sensor packet type is not supported. It should be simple enough to add though, I'll put it in the queue!

**Comment by Bjsulla** [comment]
Great!
Thank you.

**Comment by maxwellhadley** [comment]
New version 1.3.0 now published. I've added MAVERICK as a new subtype to rfx-sensor-in: it reports both the meat & fire temperatures. As I don't have a thermometer to test with, I've just used the example in the RFXCOM SDK documentation to test against. Please let me know if you find any problems, and re-open the issue if necessary.
