### ISSUE TITLE
rfxcom freezes node red 

### ISSUE THREAD

**Issue by Giaitzoglou** [maxwellhadley/node-red-contrib-rfxcom#23]
hi i did the update of the rfx and after the flow froze and i had to remove the rfxcom node .
i tried reinstaling but ow it doesnt work at all  
i get this problem and even if i install separate the serialport still when you send send the command in nodered it doenst appear any activity on the rfxcom device 

> serialport@4.0.7 install /usr/lib/node_modules/node-red-contrib-rfxcom/node_modules/rfxcom/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v46-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@4.8.4 (node-v46 ABI) (falling back to source compile with node-gyp)

**Comment by maxwellhadley** [comment]
That error is not critical - it just means there is no ready-made serialport binary for your target architecture. If there is a problem with rebuilding serialport there will be other errors: but that would have given you 'missing node' warnings in node-RED, not just disappearing data.

Please can you restart your Node-RED (with the rfxcom node in place) with the environment variable `RED_DEBUG` set to rfxcom:

    RED_DEBUG=rfxcom node-red-pi

This will turn on debug logging for the rfxcom node. I suspect it is failing to connect to your RFXtrx433E, but if you try this and send me the console output I may be able to help you better.

**Comment by maxwellhadley** [comment]
Are you making any progress?

**Comment by Giaitzoglou** [comment]
hi thanks for your feedback i tried and installed it manually(serialport) , i dont know why it couldnt being installed with rfcom node .
Now everything works perfect 
thanks again for your help

**Comment by maxwellhadley** [comment]
OK thanks, I'll close this issue.
