### ISSUE TITLE
livolo devices

### ISSUE THREAD

**Issue by Giaitzoglou** [maxwellhadley/node-red-contrib-rfxcom#34]
hi i can you please help with the commands of controling a livolo device?
i have put the thedevice id in the topic menu in the input node but up until now i can toggle the light on but it doeast stay on it closed after 1 minute.
the command i used is "toggle" i tried "on" or "off" but it doesnt do anything from node red, from the rfxcom manager it works with no problem even the "off" command .
the setting are
command : toggle 
topic : livolo/000102/1
i am looking forward to your response 
thanks 
chris

**Comment by maxwellhadley** [comment]
Which type of Livolo device is this? I don't have any actual Livolo devices here, but the information I have talks about a 'dimmer', a single-gang appliance module, and a 3-gang appliance module. To turn on, they all use 'toggle' to switch state. You can also use 'off', but this is always a 'group' command, so the unit code (last part of the topic) has to be '0' (or alternatively '+').

In the rfx-light-out node configuration, you can tell it to repeat each message after a delay. If the delay was set to 60 seconds, and the command you were sending is 'toggle', it would give the effect you describe of turning on then turning off after a minute. Is that what is happening, maybe?

**Comment by maxwellhadley** [comment]
Any further developments?

**Comment by Giaitzoglou** [comment]
thank you so much for your help everything you said was correct . i have it working now .
thanks again

**Comment by maxwellhadley** [comment]
Glad to hear it's working for you!
