### ISSUE TITLE
Security1 - KD101/RM174RF

### ISSUE THREAD

**Issue by CrowJay** [maxwellhadley/node-red-contrib-rfxcom#35]
Seems like the "rfx detector" does not pick up anything from my smoke detectors. I have tested several RM174RF and KD101 detectors without result. 

They report fine in rfxmngr

Packettype    = Security1
subtype       = KD101 smoke detector
Sequence nbr  = 0
id1-3         = 5FEA00 decimal:6285824
status        = Panic
Signal level  = 7  -64dBm

Packettype    = Security1
subtype       = RM174RF smoke detector
Sequence nbr  = 1
id1-3         = 118103 decimal:1147139
status        = Panic
Signal level  = 6  -72dBm

Thank you for maintaining this node.

**Comment by maxwellhadley** [comment]
I found the issue - there is a missing definition for PANIC in the node-rfxcom library used by node-red-contrib-rfxcom. I'll fix that and publish an update.
Thanks for spotting this!

**Comment by maxwellhadley** [comment]
Version 2.2.3 now published - should fix this issue.
