### ISSUE TITLE
Support for MCZ pellet stove

### ISSUE THREAD

**Issue by benoitdendrael** [maxwellhadley/node-red-contrib-rfxcom#41]
Would it be possible to add the support for MCZ pellet stove ? 
I don't know if others would be interested.
I have equipment and time to help you with testing and debugging.
Best Regards.

**Comment by maxwellhadley** [comment]
It should be possible - I added support for this and other thermostat types to the `node-rfxcom` package a while back, so it's mainly a question of designing the Node-RED 'API'. What sort of messages would you expect to be able to send to the stove? (there is no support for receiving MCZ messages in the RFXtrx433E). How would you expect to configure the node, e.g. set the number of fans? What use cases do you envisage?

I would probably add a new node type 'rfx-heating-out' to handle the MCZ and the other supported thermostat types as well, so the node would have to be more general, though.

**Comment by benoitdendrael** [comment]
Thank you for your reply,
I saw the functionality of thermostat4 in the node-rfxcom package, so I thought it would be possible to integrate it into the Node-RED ‘API’.

I think we need to be able to select the MCZ model type (numbers of fan)
number of fans/device address -> in the topic like "rfx-blinds-out"
and we can use a message like a list of parameters (a string) for send the functionality like this
beep=0,1 / mode=0,1,2,3 / flame power=1,2,3,4,5 / fan speed 1=0,1,2,3,4,5,6 / fan speed 2=0,1,2,3,4,5,6 / fan speed 3=0,1,2,3,4,5,6.

I envisage to use Node-RED ‘API’ to control my pellet stove,
Sending start / stop, power of fire and ventilation commands according to the temperature of the room.
If needed I can do a little documentation on the orders that can be sent to the MCZ Pellet Stove.

**Comment by maxwellhadley** [comment]
That would be helpful. I had a look at the MCZ manual when I added thermostat4, and if I remember correctly, there are some limitations, like you must have at least one fan at non-zero speed, that should be observed?

What would also be helpful is a 'history' of the commands you expect to be sending to the stove during the day, to control it in the way you want.

**Comment by benoitdendrael** [comment]
Here is a small recap of the no-air mode and the principal commands that i send to the stove during the day.
[Usage of zero fan speed.pdf](https://github.com/maxwellhadley/node-red-contrib-rfxcom/files/1754382/Usage.of.zero.fan.speed.pdf)

Don't hesitate if you need more informations or tests about the MCZ stove.

**Comment by benoitdendrael** [comment]
Max, how long do you think you can add the "'rfx-heating-out" function ?
I am really interested in this!

Best regards,

**Comment by maxwellhadley** [comment]
I haven't forgotten! A lot of other things going on at the moment so my time is limited, but I will be working on it when I get a chance

**Comment by maxwellhadley** [comment]
Benoit,

From the RFXCOM SDK documentation, the fan speed value can be 0 to 6, where 6 means 'auto'. But in the RFXCOM user guide, it states:

> 13. MCZ pellet stove.
In the Type2 firmware zip file which is available on the downloads page you will find a special firmware RFXtrxMCZ.hex that enables you to know the ID of the your MCZ remote.
Flash the RFXtrxMCZ.hex firmware in your RFXtrx433(E) and start RFXmngr. Transmit a command with the MCZ remote and you will receive the information.
The ID in this example is 81 3F 22

    Packettype    = Thermostat4
    subtype       = MCZ pellet stove 2 fans model
    Sequence nbr  = 0
    ID            = 0x813F22 decimal:8470306
    Beep          = Yes
    Fan1 speed    = 1
    Fan2 speed    = 7
    Flame power   = 1
    Command       = Off
    Signal level  = 6  -72dBm

>Flash now Type2 or Ext firmware in your RFXtrx433(E) and you can control your MCZ stove using the received ID.
Important: remove the batteries from the original remote before you start using the RFXtrx433 to control the MCZ stove!

Where the fan speed reads as 7!

Please can you try this out using your MCZ remote and find out what the actual range of fan speeds received by the RFXCOM is, including the 'auto' setting? Could you also please explain to me what the 'auto' and 'eco' stove modes are used for? I assume that if you are using to Node-RED to control the stove, it will always need to be in 'manual' mode (or 'off') so the room thermostat function can be implemented in Node-RED itself.

**Comment by maxwellhadley** [comment]
Benoit,

Which model stove do you have? I've been looking around on the MCZ site for manuals, and they differ a lot. They even make WiFi-connected models now!

**Comment by benoitdendrael** [comment]
Yes, they now manufacture wifi models! :+1: 

But I have the VIVO 80 Pellet 2012 generation, 

This is the link for the [VIVO 80 Manuals of use and installation](https://www.mczgroup.com/download/8901230200.pdf)

And I have the service manual MCZ for installation [Service-Manual_EN.pdf](https://github.com/maxwellhadley/node-red-contrib-rfxcom/files/1961705/Service-Manual_EN.pdf)

**Comment by maxwellhadley** [comment]
MCZ support added in version 2.5.0
