### ISSUE TITLE
Error message after upgrading to latest version

### ISSUE THREAD

**Issue by Mastiffen** [maxwellhadley/node-red-contrib-rfxcom#46]
I get this error message after upgrading to the latest version:

> [warn] [rfx-lights-in:Nexa-brytere] rfx-lights-in: unrecognised Lighting1 command ff

Here is my flow, that I'm using, if that can help:

`[{"id":"5b16003e.c07db8","type":"tab","label":"RFXtrx","disabled":false,"info":""},{"id":"782a62ca.db7db4","type":"rfx-sensor","z":"5b16003e.c07db8","name":"Viking-sensorer","port":"af2f38e7.9f459","topicSource":"single","topic":"TEMP7","x":114.19999694824219,"y":34,"wires":[["1d493eeb.1c7049"]]},{"id":"1d493eeb.1c7049","type":"function","z":"5b16003e.c07db8","name":"Gjøre om viking","func":"var protocol = \"Viking\";\nvar tmp = msg.payload.temperature.value;\nvar id = msg.topic.split('/')[1].split('x')[1];\nid = parseInt(id, 16);\nmsg.payload = protocol+','+id+','+tmp;\nreturn msg;","outputs":1,"noerr":0,"x":454.49998474121094,"y":44.19999694824219,"wires":[["a0df9f9f.17d3b8"]]},{"id":"8c45f92.b957d08","type":"rfx-sensor","z":"5b16003e.c07db8","name":"Oregon-sensor med barometer","port":"af2f38e7.9f459","topicSource":"single","topic":"THB1","x":148.49998474121094,"y":137.39999389648438,"wires":[["57818574.e4a2bc"]]},{"id":"57818574.e4a2bc","type":"function","z":"5b16003e.c07db8","name":"Gjøre om Oregon med barometer","func":"var protocol = \"Oregon-barometer\";\nvar id = msg.topic.split('/')[1].split('x')[1];\nid = parseInt(id, 16);\nvar tmp = msg.payload.temperature.value;\nvar fuktighet = msg.payload.humidity.value;\nvar trykk = msg.payload.pressure.value;\nmsg.payload = protocol+','+id+','+tmp+','+fuktighet+','+trykk;\nreturn msg;","outputs":1,"noerr":0,"x":478.1999969482422,"y":136,"wires":[["a0df9f9f.17d3b8"]]},{"id":"b8b22ed2.682828","type":"rfx-sensor","z":"5b16003e.c07db8","name":"Oregon-sensor uten barometer","port":"af2f38e7.9f459","topicSource":"single","topic":"TH1","x":150.49998474121094,"y":222.3999786376953,"wires":[["1861c903.589f87"]]},{"id":"1861c903.589f87","type":"function","z":"5b16003e.c07db8","name":"Gjøre om Oregon uten barometer","func":"var protocol = \"Oregon-termometer\";\nvar id = msg.topic.split('/')[1].split('x')[1];\nid = parseInt(id, 16);\nvar tmp = msg.payload.temperature.value;\nvar fuktighet = msg.payload.humidity.value;\nmsg.payload = protocol+','+id+','+tmp+','+fuktighet;\nreturn msg;","outputs":1,"noerr":0,"x":459.1999969482422,"y":223.00001525878906,"wires":[["a0df9f9f.17d3b8"]]},{"id":"a95dbc08.2b2af8","type":"rfx-lights-in","z":"5b16003e.c07db8","name":"Nexa-brytere","port":"af2f38e7.9f459","topicSource":"all","topic":"","x":98.99998474121094,"y":291.8000030517578,"wires":[["99ff777b.34937","a69d717f.5e2c7"]]},{"id":"10eb855b.4de63b","type":"rfx-lights-out","z":"5b16003e.c07db8","name":"Ovn 3","port":"af2f38e7.9f459","topicSource":"msg","retransmit":"none","retransmitInterval":20,"topic":"AC/0x008d303a/3","x":284.4999694824219,"y":373.6000061035156,"wires":[]},{"id":"62687e39.b358d8","type":"inject","z":"5b16003e.c07db8","name":"Slå på","topic":"AC/0x000cbffe/2","payload":"\"On\"","payloadType":"str","repeat":"","crontab":"","once":false,"x":100.19998168945312,"y":375.00001525878906,"wires":[["10eb855b.4de63b"]]},{"id":"6185ddf2.7289cc","type":"inject","z":"5b16003e.c07db8","name":"Slå av","topic":"AC/0x008d303a/3","payload":"\"Off\"","payloadType":"str","repeat":"","crontab":"","once":false,"x":98.99998474121094,"y":411.8000030517578,"wires":[["10eb855b.4de63b","3beed4d2.e78d84"]]},{"id":"99ff777b.34937","type":"function","z":"5b16003e.c07db8","name":"Gjøre om Nexa-brytere","func":"var protocol = \"AC\";\nvar huskode = msg.topic.split('/')[1].split('x')[1];\nvar enhet = msg.topic.split('/')[2];\nkommando = msg.payload.split('\"')[0];\nmsg.topic = 'eg/RFXtrx.Bryter.'+protocol+'.'+huskode+'.'+enhet+'.'+kommando;\nmsg.payload = '';\nreturn msg;","outputs":1,"noerr":0,"x":308.99998474121094,"y":291.8000030517578,"wires":[["51abb410.c710dc"]]},{"id":"3f65efdf.67f2a8","type":"rfx-sensor","z":"5b16003e.c07db8","name":"Regnmåler","port":"af2f38e7.9f459","topicSource":"single","topic":"RAIN2","x":88.99998474121094,"y":491.8000030517578,"wires":[["62e8b2fc.8023bc"]]},{"id":"62e8b2fc.8023bc","type":"function","z":"5b16003e.c07db8","name":"Gjøre om Oregon uten barometer","func":"var protocol = \"Regn\";\nvar regn = msg.payload.rainfall.rate.value;\nvar totaltregn = msg.payload.rainfall.total.value;\nmsg.payload = protocol+','+regn+','+totaltregn;\nreturn msg;","outputs":1,"noerr":0,"x":328.99998474121094,"y":491.8000030517578,"wires":[[]]},{"id":"322a35cd.f90eb2","type":"rfx-sensor","z":"5b16003e.c07db8","name":"Vindmåler","port":"af2f38e7.9f459","topicSource":"single","topic":"WIND2","x":84.99998474121094,"y":568.8000030517578,"wires":[["e41479a1.48209","57fe95e9.5cb114","9b9dcda2.5efe88"]]},{"id":"5a32730b.7e6b94","type":"mqtt in","z":"5b16003e.c07db8","name":"","topic":"RFXACPaa","qos":"2","broker":"25dbde39.c4ef42","x":98.99998474121094,"y":831.8000030517578,"wires":[["49339c25.02298c"]]},{"id":"49339c25.02298c","type":"function","z":"5b16003e.c07db8","name":"Omgjøring til RFXtrx-kommando","func":"msg.topic = msg.payload;\nmsg.payload = \"On\";\nreturn msg;","outputs":1,"noerr":0,"x":358.99998474121094,"y":831.8000030517578,"wires":[["72bd2d40.02203c","7272dd01.08655c"]]},{"id":"7272dd01.08655c","type":"rfx-lights-out","z":"5b16003e.c07db8","name":"RFXtrx-kommandoer","port":"af2f38e7.9f459","topicSource":"msg","retransmit":"none","retransmitInterval":20,"topic":"","x":626.9999847412109,"y":864.8000030517578,"wires":[]},{"id":"3beed4d2.e78d84","type":"function","z":"5b16003e.c07db8","name":"","func":"msg.payload = msg.payload;\nmsg.device = msg.topic;\nreturn msg;","outputs":1,"noerr":0,"x":280.99998474121094,"y":426.8000030517578,"wires":[["487223ad.c3ece4"]]},{"id":"487223ad.c3ece4","type":"debug","z":"5b16003e.c07db8","name":"","active":false,"console":"false","complete":"topic","x":462.99998474121094,"y":423.8000030517578,"wires":[]},{"id":"72bd2d40.02203c","type":"debug","z":"5b16003e.c07db8","name":"","active":false,"console":"false","complete":"true","x":571.9999847412109,"y":808.7999725341797,"wires":[]},{"id":"433cad85.8e9c3c","type":"mqtt in","z":"5b16003e.c07db8","name":"","topic":"RFXACAv","qos":"2","broker":"25dbde39.c4ef42","x":88.99998474121094,"y":891.8000030517578,"wires":[["6f96a888.defda"]]},{"id":"6f96a888.defda","type":"function","z":"5b16003e.c07db8","name":"Omgjøring til RFXtrx-kommando","func":"msg.topic = msg.payload;\nmsg.payload = \"Off\";\nreturn msg;","outputs":1,"noerr":0,"x":358.99998474121094,"y":891.8000030517578,"wires":[["7272dd01.08655c","6625704e.11382"]]},{"id":"6625704e.11382","type":"debug","z":"5b16003e.c07db8","name":"","active":false,"console":"false","complete":"true","x":564.9999847412109,"y":918.8000030517578,"wires":[]},{"id":"a0df9f9f.17d3b8","type":"mqtt out","z":"5b16003e.c07db8","name":"","topic":"eg/RFXtrx.Temperatur","qos":"","retain":"","broker":"25dbde39.c4ef42","x":868.9999847412109,"y":111.80000305175781,"wires":[]},{"id":"51abb410.c710dc","type":"mqtt out","z":"5b16003e.c07db8","name":"","topic":"","qos":"","retain":"","broker":"25dbde39.c4ef42","x":558.9999847412109,"y":291.8000030517578,"wires":[]},{"id":"e37470.0ca0e39","type":"mqtt out","z":"5b16003e.c07db8","name":"Ringeklokke","topic":"","qos":"","retain":"","broker":"25dbde39.c4ef42","x":495.1999969482422,"y":604.0000152587891,"wires":[]},{"id":"a69d717f.5e2c7","type":"debug","z":"5b16003e.c07db8","name":"","active":false,"console":"false","complete":"payload","x":282.1999969482422,"y":328.00001525878906,"wires":[]},{"id":"5e8418e1.25d638","type":"rfx-lights-in","z":"5b16003e.c07db8","name":"Nexa-brytere","port":"af2f38e7.9f459","topicSource":"single","topic":"dilldall","x":94.19998168945312,"y":659.0000152587891,"wires":[["778e6246.f341a4"]]},{"id":"778e6246.f341a4","type":"function","z":"5b16003e.c07db8","name":"Dørklokker","func":"tp = msg.topic;\ntp = tp.split('/');\nif(tp[2] === '0'){\n    msg.topic = 'eg/RFXtrx.Ringeklokke.'+tp[1].split('x')[1];\n    msg.payload = '';\n    return msg;\n}","outputs":1,"noerr":0,"x":298.49998474121094,"y":658.2000274658203,"wires":[["c6893bd3.1a4e7","ba1ce1b4.10d48","e37470.0ca0e39"]]},{"id":"c6893bd3.1a4e7","type":"debug","z":"5b16003e.c07db8","name":"","active":false,"console":"false","complete":"payload","x":495.1999969482422,"y":659.0000152587891,"wires":[]},{"id":"ba1ce1b4.10d48","type":"debug","z":"5b16003e.c07db8","name":"","active":false,"console":"false","complete":"topic","x":479.1999969482422,"y":698.0000152587891,"wires":[]},{"id":"dc3c0292.1ea85","type":"debug","z":"5b16003e.c07db8","name":"","active":false,"console":"false","complete":"payload","x":635.1999969482422,"y":523.0000152587891,"wires":[]},{"id":"f872368e.73fc2","type":"debug","z":"5b16003e.c07db8","name":"","active":false,"console":"false","complete":"topic","x":625.1999969482422,"y":558.0000152587891,"wires":[]},{"id":"e41479a1.48209","type":"function","z":"5b16003e.c07db8","name":"Node for å finne en ny type sensor","func":"tp = msg.topic;\ntp = tp.split('/');\nif(tp[0] != 'TEMP7'){\n    if(tp[0] != 'TH1'){\n        if(tp[0] != 'THB1'){\n            if(tp[0] != 'RAIN2'){\n                msg.topic = 'Vind?????';\n    return msg;\n}}}}\n\n","outputs":1,"noerr":0,"x":328.1999969482422,"y":535.0000152587891,"wires":[["9dd79dd4.f7c4f8"]]},{"id":"b36b272e.2c2568","type":"mqtt out","z":"5b16003e.c07db8","name":"","topic":"eg/RFXtrx.Vindmåler","qos":"","retain":"","broker":"25dbde39.c4ef42","x":868.1999969482422,"y":539.0000152587891,"wires":[]},{"id":"9dd79dd4.f7c4f8","type":"debug","z":"5b16003e.c07db8","name":"","active":false,"console":"false","complete":"payload","x":742.1999969482422,"y":458.00001525878906,"wires":[]},{"id":"57fe95e9.5cb114","type":"function","z":"5b16003e.c07db8","name":"Vindmåler","func":"var retning = msg.payload.wind.direction.value;\nvar vindstyrke = msg.payload.wind.speed.value;\nvar vindkast = msg.payload.wind.gust.value;\nmsg.topic = 'Vind';\nmsg.payload = retning+','+vindstyrke+','+vindkast;\nreturn msg;\n","outputs":1,"noerr":0,"x":292.1999816894531,"y":568.0000152587891,"wires":[["f872368e.73fc2","dc3c0292.1ea85"]]},{"id":"9f45ae99.4905a","type":"rfx-blinds-in","z":"5b16003e.c07db8","name":"","port":"af2f38e7.9f459","topicSource":"all","topic":"","x":79.14999389648438,"y":1073.6500091552734,"wires":[["541760a6.280fd8","418bc219.17460c"]]},{"id":"541760a6.280fd8","type":"debug","z":"5b16003e.c07db8","name":"","active":true,"console":"false","complete":"false","x":304.1499786376953,"y":1103.1501007080078,"wires":[]},{"id":"418bc219.17460c","type":"debug","z":"5b16003e.c07db8","name":"","active":true,"console":"false","complete":"false","x":307.1499786376953,"y":1056.1499786376953,"wires":[]},{"id":"9b9dcda2.5efe88","type":"debug","z":"5b16003e.c07db8","name":"","active":false,"console":"false","complete":"true","x":716.1999969482422,"y":594.0000152587891,"wires":[]},{"id":"af2f38e7.9f459","type":"rfxtrx-port","z":"","port":"/dev/ttyUSB0","rfyVenetianMode":"EU"},{"id":"25dbde39.c4ef42","type":"mqtt-broker","z":"","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"willTopic":"","willQos":"0","willPayload":"","birthTopic":"","birthQos":"0","birthPayload":""}]`

**Comment by maxwellhadley** [comment]
This message means the RFXtrx433 has received a Lighting1 packet of subtype X10 or ARC that contains a command the firmware in the transceiver itself does not understand - it gives 0xff as the command number. The rfx-lights-in node does not recognise 0xff as a valid command and so prints the message. Do you have any idea where the transmission is coming from (from the topic) and what type of device it is? What is the version of the RFX firmware you are using?

**Comment by Mastiffen** [comment]
I have none of the above, so it has to be some kind of a fluke. I think I have a pretty old firmware, V95.

**Comment by maxwellhadley** [comment]
I have just published version 2.5.0 - this adds a checkbox on the config node editor to enable debug output, instead of having to set the RED_DEBUG environment variable. It should make it easier to track down problems like this
