### ISSUE TITLE
rfx-meter - wireless energy monitors OWL

### ISSUE THREAD

**Issue by mac-d** [maxwellhadley/node-red-contrib-rfxcom#47]
Hello, I have two wireless energy monitors from OWL in use.
After the update, I only get data from a current meter.
The RFXCOM receives both transmitters.
What can I do?

**Comment by maxwellhadley** [comment]
I have made no change to the energy meter handling in the recent update, it should not have affected your OWLs. What version were you running previously?

**Comment by mac-d** [comment]
Hello, unfortunately I do not know that.
I did an update on both the RFXcom and node-red.
I just noticed that with the RFXcom Manager both ammeters are displayed.
If I only use the rfx-meter and debug, only one sender will be displayed.
nice greeting dieter

**Comment by maxwellhadley** [comment]
Please first check the rfx-mter node is set to 'listen for data messages from any address'. I don't see why that would have changed, though.

I would like to check the messages are getting through to Node-RED from the RFXtrx433E. Please can you stop Node-RED, then set the environment variable `RED_DEBUG=rfxcom` and re-start Node-RED. This will send extra debug messages from the `rfxcom` module to the console output.

OWL sensors send messages of different types, depending on the model:

- OWL CM113 = message starting 0D, 59, 01, ..., id1, id2
- OWL CM119/160 = message starting 11, 5A, 01, ... ,id1, id2
- OWL CM180 = message starting 11, 5A, 02, ..., id1, id2
- OWL CM180i = message starting 13, 5B, 01, ..., id1, id2

Where ... is a number which counts up with each message, and id1, id2 are the address or id bytes of the sensor.

If you look at the console output for lines like:

    [rfxcom] on /dev/cu.usbserial-A1R1A6A - Received: 0B,11,00,00,00,1E,F1,CE,01,00,00,70

(where your device port will be different, obviously) these are the actual bytes returned by the RFXtrx433E. If you see messages from both sensors, it's a problem with node-red-contrib-rfxcom. If not, it's something to do with the receiver itself.

**Comment by mac-d** [comment]
Hello, Unfortunately, I'm not so good with the Node-Red system.
Where do I have to make the entry RED_DEBUG = rfxcom?
I use Node-Red via ioBroker.
Thank you Dieter

**Comment by mac-d** [comment]
Many Thanks.
I'm waiting for the new version
