### ISSUE TITLE
rfx-meter node doesn't appear to support actual RFXMeter devices?

### ISSUE THREAD

**Issue by martynwendon** [maxwellhadley/node-red-contrib-rfxcom#51]
I recently started using node-red-contrib-rfxcom alongside my older RFXLan (xPL) devices and alongside Domoticz.

I've slowly been mirroring the data into node-red from all those sources which makes for a very robust and reliable system.

I noticed that the rfx-meter node doesn't appear to support actual RFXMeter devices (0x71), for example the old RFXMeter / RFXPulse combination, or the WPC3 device from foogadgets.

Would that be a quick fix to add that to the rfx-meter node?

**Comment by maxwellhadley** [comment]
That should be possible, although the packet subtypes seem to be used differently from just about everything else, so it would need special-case handling in the meter node. The SDK documentation is a bit sketchy, too - and there is nothing at all on the RFXCOM website about the unit. Do you have a copy of the RFX-meter user manual you could send somehow?

Am I correct in my understanding that you have to press buttons in some combination on the RFX meter to set the reporting interval, calibration factors, address and so forth? It appears to be receive only on the RFXtrx433E

**Comment by martynwendon** [comment]
The RFXMeter / RFXPulse are *really* old now, I couldn't actually remember how they work, mine have been running for > 10 years!

I managed to dig out the manual and refresh my memory - there is a push-button interface to configure it but they are also bi-directional so could be configured using software.  I do recall carrying out that operation when I first got the device, I believe I used an old application called xPLRFX with the old USB RFX 433 transceiver (another very old device!)

The foogadgets WPC3 device simply mimics an RFXMeter device in terms of transmission, but that's one-way only and the configuration is hardcoded in the device (I've attached the manual for that too).


In terms of what the rfx-meter node would need to do, I guess taking a look at the Domoticz source would give a reasonable clue, since both the original RFXMeter and the WPC3 variants work well there.  From memory the Vera LUA based plugin also supported them, although I've not used that for some time, but it's a little easier to understand than the domoticz source.

https://github.com/domoticz/domoticz/search?q=rfxmeter&unscoped_q=rfxmeter

http://code.mios.com/trac/mios_rfxtrx/browser/trunk



[ManualWPC3.pdf](https://github.com/maxwellhadley/node-red-contrib-rfxcom/files/2051252/ManualWPC3.pdf)


[RFXMeter.pdf](https://github.com/maxwellhadley/node-red-contrib-rfxcom/files/2051220/RFXMeter.pdf)
[RFXPulse module.pdf](https://github.com/maxwellhadley/node-red-contrib-rfxcom/files/2051221/RFXPulse.module.pdf)
