### ISSUE TITLE
'level xx%' command no longer accepted

### ISSUE THREAD

**Issue by driveland** [maxwellhadley/node-red-contrib-rfxcom#55]
With previous versions I was able to set the dim level of a lamp with the command 'level 25%'. After I upgraded to the latest version, this command doesn't work anymore. Instead I get an error message in the debug window "Don't understand dimming command 'level 25%'". I tried alternative commands like 'level 0.25' or just '25%', but none of these are accepted.

**Comment by maxwellhadley** [comment]
That should still work - I will check it. What is the type of lamp you are trying to control?

**Comment by driveland** [comment]
The lamp is just a regular bulb attached to a wireless dimmer module from a brand called 'klik-aan-klik-uit'. I have two of these dimmers. I have been using them for about 2 years now. It worked just fine up and until this week when I upgraded the rfxcom module in node-red on my Raspberry Pi. Using the 'on'/'off' command on the dimmers works, so commands are received. 'On' command sets it to its last known dim level. Just the 'level' command malfunctions and the error I mentioned in my first comment is displayed in the debug window in node-red pointing to the rfxcom module..

**Comment by maxwellhadley** [comment]
This was a bug introduced last September, I got the sense of a test wrong, sorry! Now fixed in 2.6.1 which I just published

**Comment by driveland** [comment]
I downloaded version 2.6.1 and tested the level setting. I works just as before. Thanks!
