### ISSUE TITLE
node-red-contrib-rfxcom vs node-rfxcom dependencies

### ISSUE THREAD

**Issue by erspearson** [maxwellhadley/node-red-contrib-rfxcom#6]
More of an FYI than an issue. Just moving some flows from Windows to a RPi Bv1 for production on a clean-ish install of Jessie.

Node-RED version: v0.13.4
Node.js  version: v0.10.29
Linux 4.1.19+ arm LE

Possibly something to do with the merge of node-rfxcom back into the original being in-flight?

rfxcom _**is**_ working in nodered. Hence just an FYI.

```
pi@raspberrypi:~/.node-red$ npm list
/home/pi/.node-red
└── (empty)

pi@raspberrypi:~/.node-red$ npm install node-red-contrib-rfxcom
> serialport@2.0.6 install /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/rfxcom/node_modules/serialport
> node-pre-gyp install --fallback-to-build

make: Entering directory '/home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/rfxcom/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  COPY Release/serialport.node
  COPY /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/rfxcom/node_modules/serialport/build/Release/node-v11-linux-arm/serialport.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/rfxcom/node_modules/serialport/build'
node-red-contrib-rfxcom@1.1.2 node_modules/node-red-contrib-rfxcom
└── rfxcom@0.8.1 (serialport@2.0.6)
pi@raspberrypi:~/.node-red$ npm list
/home/pi/.node-red
└─┬ node-red-contrib-rfxcom@1.1.2
  ├── UNMET DEPENDENCY node-rfxcom@git+https://github.com/maxwellhadley/node-rfxcom.git
  └── rfxcom@0.8.1 extraneous (git+https://github.com/maxwellhadley/node-rfxcom.git#c1021dd31023b855e08954decc3389ace28d17e4)

npm ERR! missing: node-rfxcom@git+https://github.com/maxwellhadley/node-rfxcom.git, required by node-red-contrib-rfxcom@1.1.2
npm ERR! extraneous: rfxcom@0.8.1 /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/rfxcom
```

**Comment by maxwellhadley** [comment]
I think what is going on here is that node-red-contrib-rfxcom declares a dependency on 'node-rfxcom', sourced from my Github, but the package.json it pulls in names the package as 'rfxcom'. Hence the one is missing and the other is extraneous. But they are, in fact, different names fro the same package.

I am indeed in the middle of merging the two forks of rfxcom back together, as Kevin McDermott has now added me as a package maintainer. indeed, had the washing machine not expired last weekend it would probably be done by now. Probably within a week I will be able to publish a new version of node-red-contrib-rfxcom that no longer depends on my Github fork.

**Comment by erspearson** [comment]
Kate will help...
https://www.youtube.com/watch?v=GZnA4jHuyzs
