### ISSUE TITLE
lighting2 not supported?

### ISSUE THREAD

**Issue by 6wheels** [maxwellhadley/node-red-contrib-rfxcom#60]
Hi,
I'm trying to migrate from OpenHAB to Node-RED, or at least check if I can get everything to work with Node-RED.
I have several Chacon On/Off switches to control both lights and heaters.
In OpenHAB they are declared liked this: 
`channel="rfxcom:lighting2:a5a65bd4:command"`
I thought that a simple topic like: `/lighting2/a5a65b/d4` would work, but I actually get the following error: `[warn] [rfx-lights-out:da70600b.8c6b5] rfx-lights-out : device type 'LIGHTING2' is not supported`

Am I missing something? or Lighting2 is simply not supported?

Thanks in advance.

**Comment by maxwellhadley** [comment]
There are two different types of Chacon switches: the older type uses 'lighting1' protocol, and has thumbwheel switches to set the address, the newer type uses 'lighting2' protocol and sets the address by 'pairing' with a transmitter. The topic name for the old type is CHACON, while the topic name for the new type is AC. I think `/ac/a5a65b/d4` is what you want. (Note that topic names are not case-sensitive)

**Comment by 6wheels** [comment]
Thanks for your answer.
I managed to make it work!
I had already tried the `/ac` topic but I was using the wrong device address... I was using the OpenHAB's internal identifier instead of the one declared in the RFXCom.

It works like a charm now.

Thanks for your work, migration seems possible now ;)
