### ISSUE TITLE
Issue with script path

### ISSUE THREAD

**Issue by nicolasferry** [maxwellhadley/node-red-contrib-rfxcom#66]
Hello, 
Since the last update I got the following error when installing the package (either using npm install node-red-contrib-rfxcom or using node-red palette management):

npm install node-red-contrib-rfxcom
npm ERR! path /root/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/rfxcom/bin/find-rfxcom
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/root/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/rfxcom/bin/find-rfxcom'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Is there anything I missed?

Many thanks!

**Comment by nicolasferry** [comment]
Yes thanks, it works :)

**Comment by maxwellhadley** [comment]
I will close this for now and maybe reopen it when I have investigated further
