### ISSUE TITLE
Please add Transmit node for KD101 smoke detector

### ISSUE THREAD

**Issue by Mickelin01** [maxwellhadley/node-red-contrib-rfxcom#68]
Using the rfxtrx manager it is possible to send a command to trigger the KD101 smoke detector siren. Thus, the smoke detectors can be tested and used as multi purpose alarm sirens. It would be great if you would add a transmit node with the same capability to the node-red-contrib-rfxcom. Thanks in advance!

**Comment by maxwellhadley** [comment]
It should be possible, I suppose, and now at least one person wants it...

**Comment by Mickelin01** [comment]
Yes, that would be fantastic! Let me know if I can help.

**Comment by maxwellhadley** [comment]
I have just pushed branch handle-zombie-x10-PIRs to GitHub if you want to try the new rfx-alarm-out node!

**Comment by Mickelin01** [comment]
Fantastic! Now I have my weekend all planned. :-) 

Med vänlig hälsning
Michael

**Comment by maxwellhadley** [comment]
Should now work
