### ISSUE TITLE
Upgrade Issue

### ISSUE THREAD

**Issue by apb2019** [maxwellhadley/node-red-contrib-rfxcom#69]
Trying to upgrade from 2.61 to 2.63 via Node Red Manage Pallet function. When clicking on the install button I get the following error messages in the console

9 Jan 15:36:12 - [info] Upgrading module: node-red-contrib-rfxcom to version: 2.6.3
9 Jan 15:36:36 - [warn] Installation of module node-red-contrib-rfxcom failed:
9 Jan 15:36:36 - [warn] ------------------------------------------
9 Jan 15:36:36 - [warn] npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm ERR! path /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/.bin/find-rfxcom
npm ERR! code EEXIST
npm ERR! Refusing to delete /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/.bin/find-rfxcom: is outside /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/rfxcom and not a link
npm ERR! File exists: /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/.bin/find-rfxcom
npm ERR! Move it away, and try again.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-09T15_36_36_896Z-debug.log

Also tried closing node red & using npm with the same result

pi@raspberrypi:~/.node-red $ npm install node-red-contrib-rfxcom
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! path /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/.bin/find-rfxcom
npm ERR! code EEXIST
npm ERR! Refusing to delete /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/.bin/find-rfxcom: is outside /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/rfxcom and not a link
npm ERR! File exists: /home/pi/.node-red/node_modules/node-red-contrib-rfxcom/node_modules/.bin/find-rfxcom
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-09T15_44_08_950Z-debug.log

**Comment by apb2019** [comment]
I manually deleted the two files as suggested and re-ran the update via the pallet manager and the update ran without any problems. Tx for the quick fix

**Comment by GoSpursGoNL** [comment]
Removing the two files worked perfectly for me as well, thanks.
