### ISSUE TITLE
rfx-detector node

### ISSUE THREAD

**Issue by apb2019** [maxwellhadley/node-red-contrib-rfxcom#72]
I have some RF light switches (PCB says CreaJian-X21) which I would like to use. Though light switches, RFXmngr identifies the transmissions as being X10 Security1 packet types so I have used the rfx-detector node to feed into my flow. Unfortunately the detector node only picks up the first transmission (topic: "X10_DOOR/device id", payload: "Alarm") and ignores any further transmissions from the switch - is this correct? 
The following is the rfxmgr output
 
Packettype    = Security1
subtype       = X10 security
Sequence nbr  = 0
id1-3         = 52F300 decimal:5436160
status        = Alarm
battery level = OK
Signal level  = 7  -64dBm

**Comment by apb2019** [comment]
If I understand #64 correctly it’s a similar situation as there is no difference between successive messages sent by the switch (and no heartbeat). The switch has one button which always sends the same signal each time it’s activated. When the paired receiver receives the signal, it toggles the connected light to the opposite state ie from Off to On or vice versa. Consequently other than the time stamp, the output from rfxcom is always the same ie “status = alarm” for every message received. Hope that helps

**Comment by maxwellhadley** [comment]
In that case the next release should fix it: I will use the message details you posted to make a simulation for test purposes. Hopefully any day now, if I can find a spare couple of hours...

**Comment by apb2019** [comment]
Tx, I look forward to it. Happy to test beforehand if it helps

**Comment by maxwellhadley** [comment]
Should be working now

**Comment by apb2019** [comment]
Hi, update downloaded and working well. Tx for the quick fix
