### ISSUE TITLE
RFY Venetian mode error

### ISSUE THREAD

**Issue by pabloreadi** [maxwellhadley/node-red-contrib-rfxcom#75]
Hello, I'm trying to use rfx-blinds-out but when deploy I Receive this error:
TypeError: Cannot read property 'rfyVenetianMode' of null

I changed to EU and US, but I have the same error.

Why?

**Comment by maxwellhadley** [comment]
Which version of `node-red-contrib-rfxcom` are you using? I changed the way Venetian blinds mode worked at one point, and it would be helpful to know if you are using the old way or the new.

Thanks

**Comment by pabloreadi** [comment]
Hello Max, I don't have the error now, I think  when I was trying several configurations. 
By the way the version is v0.19.5

**Comment by maxwellhadley** [comment]
OK - it may be that somehow you got into a state where the blinds node was trying to use a device configuration node that didn't exist, possibly because you had deleted it. That is about the only thing I can see that would have given rise to this particular error message
