### ISSUE TITLE
Receive %opening curtain

### ISSUE THREAD

**Issue by pabloreadi** [maxwellhadley/node-red-contrib-rfxcom#77]
Hello, can I receive the information of the position of the curtain with some node?

**Comment by maxwellhadley** [comment]
The `rfx-blinds-in` node can receive messages from some (but not all) types of curtain & blinds remote control handsets. This lets you react to 'open' and 'close' commands sent from the remote, updating your record of the curtain position. However, there is no way of knowing the actual physical position of the curtains, as the curtain motors do not include a radio transmitter.

**Comment by pabloreadi** [comment]
I'm using somfy with your contribute of node red and RFXtrx433XL to open and close my curtain. 
I think the somfy motor have radio transmitter, I'll try `rfx-blinds-in` if I receive the actual physical position. I don't understand why the curtain remote control send the position, the motor must be inform the position, don't you?

**Comment by maxwellhadley** [comment]
Unfortunately the RFXtrx433 devices cannot receive the RFY protocol used by Somfy, so there is no way to know what commands are being sent from the remote control. I believe this is because Somfy use a different radio channel to most other devices. Also, as far as I know, the Somfy motors are receive-only.

**Comment by VincentSC** [comment]
Correct, the Somfy devices that are controlled via "RFY" are receive only. After the control is programmed correctly, it will fully go to the upper position with command "up" and lower position with command "down" - AFAIK it's not possible to open it halfway.

**Comment by VincentSC** [comment]
Did not know. Somfy has a stop-position besides "up" and "down". See the manual how to program this position. Unfortunately it does not have multiple stop-positions.
