### ISSUE TITLE
Node-RED beginner

### ISSUE THREAD

**Issue by benoitdudu** [maxwellhadley/node-red-contrib-rfxcom#81]
Hi,

I am new to node-red so I probably do not understand how it should work.
I would like to use node-red-contrib-rfxcom for my MCZ pellet stove. I saw that another 'benoit' reached to use it... it appear that having the same first name is not enough.

Currently my flow consists of:
- an inject node, where I set the 'Payload' and the 'Topic' fields as follow.
Payload: it is a JSON string
`{
    "id": "0xe8e074",
    "type": "rfx-heat",
    "beep": false,
    "fanSpeed": [
        1,
        1,
        6
    ],
    "flamePower": 1,
    "mode": 1
}`
Topic: MCZ_PELLET_STOVE_2_FAN
- rfx-heat-out:
Serial Port: COM5
Address: get address from message topic
Name: titi rfx-heat

The output of my 'inject' node is connected to the input of the 'rfx-heat-out' node.

When I delpoy my flow, I get the following messages that tell me the connection is OK:
**17 Aug 09:56:04 - [info] Stopping flows
17 Aug 09:56:04 - [rfxcom] on COM5 - Cleared command message queue
17 Aug 09:56:04 - [info] Stopped flows
17 Aug 09:56:04 - [info] Starting flows
17 Aug 09:56:04 - [info] Started flows
17 Aug 09:56:04 - [info] [rfx-heat-out:titi rfx-heat] connecting to COM5
17 Aug 09:56:09 - [rfxcom] on COM5 - Sent    : 0D,00,00,00,00,00,00,00,00,00,00,00,00,00
17 Aug 09:56:10 - [rfxcom] on COM5 - Sent    : 0D,00,00,01,02,00,00,00,00,00,00,00,00,00
17 Aug 09:56:10 - [rfxcom] on COM5 - Received: 14,01,00,01,02,5F,22,00,00,00,40,03,00,1C,10,5E,46,58,43,4F,4D
17 Aug 09:56:10 - [rfxcom] on COM5 - Sent    : 0D,00,00,02,07,00,00,00,00,00,00,00,00,00
17 Aug 09:56:10 - [rfxcom] on COM5 - Received: 14,01,07,02,07,43,6F,70,79,72,69,67,68,74,20,52,46,58,43,4F,4D
17 Aug 09:56:10 - [rfxcom] on COM5 - Copyright RFXCOM
17 Aug 09:56:10 - [rfxcom] on COM5 - Started command message queue
17 Aug 09:56:10 - [info] [rfx-heat-out:titi rfx-heat] connected: Serial port COM5**

But when I click on the 'inject' node I get a message:
**17 Aug 10:07:50 - [warn] [rfx-heat-out:titi rfx-heat] Error: Invalid deviceId format**

What do I miss? How to define a correct deviceId?

Best Regards,
Benoît

**Comment by benoitdudu** [comment]
Hi again,

After several tries I modifed my 'inject' node as follow:
`{
    "beep": false,
    "fanSpeed": [
        1,
        1,
        6
    ],
    "flamePower": 1,
    "mode": 1
}`
And the 'rfx-heat-out' as follow:
Serial Port: COM5
Address: **send all command to the same address
MCZ_PELLET_STOVE_2_FAN/0x123456**
Name: titi rfx-heat

This seems better.
It is currently a bit hot to check it.

Thank you for providing us this feature.

**Comment by maxwellhadley** [comment]
Yeah, the ID or 'address' always forms part of the message topic - this is universal throughout `node-red-contrib-rfxcom`
