### ISSUE TITLE
Non compatibile with latest Node-Red release v 1.0

### ISSUE THREAD

**Issue by grishmanCH** [maxwellhadley/node-red-contrib-rfxcom#85]
This node is not anymore functioning under new Node-red release 1.0.1
Would be great if you can adjust the code to make it function again.
Many thanks in advance.
![rfx_issue](https://user-images.githubusercontent.com/44230283/66656735-de1bc480-ec3e-11e9-8abd-7b2e97cf864d.JPG)

**Comment by maxwellhadley** [comment]
What exactly goes wrong? Did you upgrade to Node-RED 1.0.1 and break a working flow, or are you unable to install the nodes? I haven't tried 1.0.1 here yet - I'm in the process of moving *everything* to a new computer and I didn't want to make the attempt the move is completed.

**Comment by grishmanCH** [comment]
I have installed Node red v 1.0 on top of older old one (0.20.7) and from my palette only rfxcom and base64 nodes gave the messages that they are no longer be used. Now i have downgraded back to 0.20.7 to use the rfxcom node, since plenty of automation depends on it. I will install one more instance of Node Red parallel to check if i can install the rfxcom node fresh. Will let you know the outcome.

**Comment by grishmanCH** [comment]
I have made a fresh install of node red v 1.0.1 and also installed the rfxcom node new - without any problem. After that I have re-imported my older flows and everything worked just fine. So i will close the issue now.
