### ISSUE TITLE
specifying a time-out

### ISSUE THREAD

**Issue by VincentSC** [maxwellhadley/node-red-contrib-rfxcom#93]
Often got a problem that the initiation goes wrong or takes very long after redeployment. In other words: it silently fails and I have no way to be warned.

Would it be possible to set a timeout, after which the USB-connection is closed and then reconnects?

**Comment by maxwellhadley** [comment]
A timeout mechanism is already present, but it just repeats indefinitely until the RFXtrx433 is reconnected. If you want to take specific action, use a `status` node, configured to report status from one of your rfxcom nodes (any one will do, they all report the same status). This will generate a message each time the status changes. You may be able to use these messages to handle your error - however the problem you describe shouldn't be occurring like that!
