### ISSUE TITLE
Battery Level

### ISSUE THREAD

**Issue by gaetan29** [maxwellhadley/node-red-contrib-rfxcom#94]
Hi,
Is there a way to retrieve the battery level (or at least its status) of an 433 Mhz device ?
"Battery" tag is showing undet RFXmngr.
Thanks

![IMG_1298](https://user-images.githubusercontent.com/788375/85530355-2aad0180-b60e-11ea-88bd-ac3258e47cc3.JPG)

**Comment by maxwellhadley** [comment]
Yes, both RSSI (signal level) and battery status, if available, are present as properties of the `status` field of the message object. Not all devices send battery status, but environmental sensors like the ones you show generally do. This is a packet from a remote control, which doesn't send battery status:

![image](https://user-images.githubusercontent.com/6557194/85565047-ad41bb00-b626-11ea-98cf-d7fb9b9ceab8.png)

**Comment by gaetan29** [comment]
Hi,
I do use the "RFX Sensor" node ... and only get the following data (see attached screenshots).... nothing about payload, battery status ...
Regards

![RFX01](https://user-images.githubusercontent.com/788375/85571692-a4f07c80-b634-11ea-9b95-87d0183879c3.png)
![RFX02](https://user-images.githubusercontent.com/788375/85571697-a5891300-b634-11ea-9822-7480a8454d6a.png)

**Comment by maxwellhadley** [comment]
You need to set the debug node to show all message properties, not just `payload`. Double-click the debug node, and set the Output to 'complete message object':

![image](https://user-images.githubusercontent.com/6557194/85573229-9d79a500-b62d-11ea-9b84-7cb6b2c61573.png)

**Comment by gaetan29** [comment]
I see... I can indeed see everything now. Many thanks.

**Comment by maxwellhadley** [comment]
You're welcome!
