### ISSUE TITLE
I can not see the full topic.

### ISSUE THREAD

**Issue by vampywiz17** [maxwellhadley/node-red-contrib-rfxcom#95]
Hello there,

I try to set a remote controller. it working well on rfxcom manager:

```
2020. 07. 02. 11:40:19:145= 09190604563801030178
Packettype    = BLINDS1
subtype       = DC106
Sequence nbr  = 4
id1-4         = 5638010 decimal:90406928
Unit          = 3
Command       = Close
Signal level  = 7  -64dBm
```

But in Node-RED i only see this:

```
2020. 07. 02. 23:57:54node: f87d946e.5155a8
BLINDS_T6/0x563801 : msg.payload : string[4]
"Close"
```

The problem that the Topic full lenght is not visible. Not possible to set the Unit, because it not visisble.

It possible to fix this?

**Comment by maxwellhadley** [comment]
This is indeed a genuine bug - well spotted! I had added the extra BLINDS1 subtypes as they were released over the years, but not kept up with the changes to which are received. Currently only subtypes 0x00, 0x01, and 0x03 handle unit codes - I will add _all_ of the remaining (0x06, 0x07, 0x08, 0x09, 0x0c, 0x0d, 0x0e, 0x0f, 0x10 and 0x11) even though only a few of them are actually received. Hopefully I won't get caught out again!

Thanks for reporting this!

**Comment by vampywiz17** [comment]
@maxwellhadley 

Thanks a lot! I wait the next release :)

**Comment by maxwellhadley** [comment]
Published 2.11.0 to npm - hopefully this will fix it

**Comment by maxwellhadley** [comment]
Two weeks & no complaints so I will close the issue :)

**Comment by vampywiz17** [comment]
@maxwellhadley Sorry for that. i only now test it. Working well with new release! Thanks a lot!
